on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: xujunregistry.azurecr.io
        username: ${{ secrets.acr_xujunregistry_username }}
        password: ${{ secrets.acr_xujunregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t xujunregistry.azurecr.io/xujunk8s1:${{ github.sha }}
        docker push xujunregistry.azurecr.io/xujunk8s1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_xujunk8s1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep xujunk8s17bed | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace xujunk8s17bed`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: xujunk8s17bed
        container-registry-url: xujunregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_xujunregistry_username }}
        container-registry-password: ${{ secrets.acr_xujunregistry_password }}
        secret-name: xujunk8s1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: xujunk8s17bed
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          xujunregistry.azurecr.io/xujunk8s1:${{ github.sha }}
        imagepullsecrets: |
          xujunk8s1dockerauth